Make .....................................................
New/Used ....................................
Invoice Price ............................................................
Model/Cc Rating ................................... Less: Discounts .......................................................
Year of Manufacture .............................. Net Cost ..................................................................
Valuation Amount .................................
(Where Applicable) Add: Accessories/Other ..........................................
Total Cost ................................................................
Tick to confirm
Insurance through I&M Insurance
Less: Deposit ............................................................
Agency Ltd
Balance of Cost .......................................................
Interested in Insurance Finance (IPF)
HIRE PURCHASE FACILITY (For Official Use)
Loan Amount Applied: Pricing Agreed:
Tenor of Loan: Repayment Frequency:
Repayment Amount: Mode of Payment:
Security Offered:
Guarantor’s Name (If any) ........................................................................................................
Details of security provided by guarantor (If any): ....................................................................