# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-22 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='additonalInfoCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholders', models.CharField(max_length=100)),
                ('annual_tunover', models.IntegerField()),
                ('annual_profit', models.IntegerField()),
                ('associate_companies', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='additonalInfoIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('name_employer', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('years', models.IntegerField()),
                ('marital_status', models.CharField(max_length=100)),
                ('spouse', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=200)),
                ('income', models.IntegerField()),
                ('spouse_income', models.IntegerField()),
                ('living_expenses', models.IntegerField()),
                ('loan_payment', models.IntegerField()),
                ('income_business', models.IntegerField()),
                ('others', models.IntegerField()),
                ('disposable_income', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('User', models.AutoField(primary_key=True, serialize=False)),
                ('yourname', models.CharField(blank=True, max_length=50)),
                ('passport', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('p_o_box', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('city_town', models.CharField(max_length=50)),
                ('physical_address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('home_officemobile', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('tenant', models.CharField(max_length=50)),
                ('tp_o_box', models.CharField(max_length=50)),
                ('tpostalcode', models.CharField(max_length=50)),
                ('tphonenumber', models.CharField(max_length=50)),
                ('business', models.CharField(max_length=50)),
                ('business2', models.CharField(max_length=50)),
                ('business3', models.CharField(max_length=50)),
                ('yrbusiness', models.CharField(max_length=50)),
                ('introby', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='applicantBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('od_limit', models.IntegerField()),
                ('outstanding_loans', models.IntegerField()),
                ('bank_name2', models.CharField(default='Add another bank name', max_length=200)),
                ('branch2', models.CharField(max_length=100)),
                ('account_number2', models.IntegerField()),
                ('od_limit2', models.IntegerField()),
                ('outstanding_loans2', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='asset_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('new_used', models.CharField(max_length=100)),
                ('invoice_price', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('less', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('valuation', models.IntegerField()),
                ('add', models.CharField(max_length=100)),
                ('insurance', models.BooleanField(default=True)),
                ('interested', models.BooleanField(default=True)),
                ('total', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('pricing', models.IntegerField()),
                ('loan', models.IntegerField()),
                ('repayment', models.IntegerField()),
                ('repayment_amount', models.IntegerField()),
                ('mode_payment', models.IntegerField()),
                ('guarantor', models.CharField(max_length=100)),
                ('security', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('postal_address', models.IntegerField()),
                ('telephone_number', models.IntegerField()),
                ('invoice_number', models.IntegerField()),
                ('sales_person', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealername', models.CharField(max_length=50)),
                ('postaladdress', models.CharField(max_length=50)),
                ('invoiceno_date', models.CharField(max_length=50)),
                ('salesperson', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Facility_type', models.CharField(max_length=50)),
                ('sanctioned_limit', models.CharField(max_length=50)),
                ('current_outstanding', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reistration', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('loan_balance', models.IntegerField()),
                ('financed_by', models.CharField(max_length=100)),
                ('the_property', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('lr_number', models.IntegerField()),
                ('approximate_value', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
