# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='additonalInfoCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholders', models.CharField(max_length=100)),
                ('annual_tunover', models.IntegerField()),
                ('annual_profit', models.IntegerField()),
                ('associate_companies', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='additonalInfoIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('name_employer', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('years', models.IntegerField()),
                ('marital_status', models.CharField(max_length=100)),
                ('spouse', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=200)),
                ('income', models.IntegerField()),
                ('spouse_income', models.IntegerField()),
                ('living_expenses', models.IntegerField()),
                ('loan_payment', models.IntegerField()),
                ('income_business', models.IntegerField()),
                ('others', models.IntegerField()),
                ('disposable_income', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50)),
                ('IDENTIFICATION', models.CharField(help_text='ID/PASSPORT/UNC/CERT. OF REG NO.', max_length=50)),
                ('PIN', models.CharField(help_text='PIN NUMBER', max_length=50)),
                ('CITY', models.CharField(help_text='CITY/TOWN', max_length=50)),
                ('PHYSICAL_ADDRESS', models.CharField(help_text='LOACTION/ROAD', max_length=50)),
                ('MOBILE', models.IntegerField(help_text='TEL. MOBILE')),
                ('TEL_HOME', models.IntegerField(help_text='TEL. HOME/OFFICE NO.')),
                ('OWNER', models.CharField(help_text='OWNER/TENANT', max_length=50)),
                ('TENANT', models.CharField(help_text='IF TENANT:(NAME OF LANDLORD)', max_length=50)),
                ('P_O_BOX', models.CharField(help_text='TENANT P.O.BOX', max_length=50)),
                ('POSTALCODE', models.CharField(help_text='TENANT POSTAL CODE', max_length=50)),
                ('PHONE_NO', models.IntegerField(help_text='TENANT PHONE NUMBER')),
                ('BUSINESS', models.CharField(help_text='NATURE OF BUSINESS', max_length=50)),
                ('YR_BUSINESS', models.CharField(help_text='YEAR OF BUSINESS ESTABLISHED', max_length=50)),
                ('INTRODUCED_BY', models.CharField(max_length=50)),
                ('PURPOSE_OF_ASSET_BEING_PURCHASED', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='applicantBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='banki', max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('od_limit', models.IntegerField()),
                ('outstanding_loans', models.IntegerField()),
                ('bank_name2', models.CharField(default='Add another bank name', max_length=200)),
                ('branch2', models.CharField(max_length=100)),
                ('account_number2', models.IntegerField()),
                ('od_limit2', models.IntegerField()),
                ('outstanding_loans2', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='asset_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('new_used', models.CharField(max_length=100)),
                ('invoice_price', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('less', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('valuation', models.IntegerField()),
                ('add', models.CharField(max_length=100)),
                ('insurance', models.BooleanField(default=True)),
                ('interested', models.BooleanField(default=True)),
                ('total', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('pricing', models.IntegerField()),
                ('loan', models.IntegerField()),
                ('repayment', models.IntegerField()),
                ('repayment_amount', models.IntegerField()),
                ('mode_payment', models.IntegerField()),
                ('guarantor', models.CharField(max_length=100)),
                ('security', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('postal_address', models.IntegerField()),
                ('telephone_number', models.IntegerField()),
                ('invoice_number', models.IntegerField()),
                ('sales_person', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealername', models.CharField(max_length=50)),
                ('postaladdress', models.CharField(max_length=50)),
                ('invoiceno_date', models.CharField(max_length=50)),
                ('salesperson', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Facility_type', models.CharField(max_length=50)),
                ('sanctioned_limit', models.CharField(max_length=50)),
                ('current_outstanding', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reistration', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('loan_balance', models.IntegerField()),
                ('financed_by', models.CharField(max_length=100)),
                ('the_property', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('lr_number', models.IntegerField()),
                ('approximate_value', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
