# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-22 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
