# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantbankdetails',
            options={'verbose_name_plural': 'ApplicantBankDetails'},
        ),
        migrations.RemoveField(
            model_name='additonalinfocompany',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='additonalinfoindividual',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='applicantbankdetails',
            name='account_number2',
        ),
        migrations.RemoveField(
            model_name='applicantbankdetails',
            name='bank_name2',
        ),
        migrations.RemoveField(
            model_name='applicantbankdetails',
            name='branch2',
        ),
        migrations.RemoveField(
            model_name='applicantbankdetails',
            name='od_limit2',
        ),
        migrations.RemoveField(
            model_name='applicantbankdetails',
            name='outstanding_loans2',
        ),
        migrations.RemoveField(
            model_name='applicantbankdetails',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='asset_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dealersupplier',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='othercredit',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='user_id',
        ),
        migrations.AddField(
            model_name='additonalinfocompany',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='additonalinfoindividual',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='applicantbankdetails',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='asset_details',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='dealersupplier',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='document',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='othercredit',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
        migrations.AddField(
            model_name='properties',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_details.Applicant'),
        ),
    ]
