# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0002_auto_20190725_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset_details',
            new_name='AssetDetails',
        ),
        migrations.AlterModelOptions(
            name='additonalinfocompany',
            options={'verbose_name_plural': 'additonalInfoCompany'},
        ),
        migrations.AlterModelOptions(
            name='additonalinfoindividual',
            options={'verbose_name_plural': ' AdditonalInfoIndividual'},
        ),
        migrations.AlterModelOptions(
            name='assetdetails',
            options={'verbose_name_plural': ' AssetDetails'},
        ),
        migrations.AlterModelOptions(
            name='dealersupplier',
            options={'verbose_name_plural': ' DealerSupplier'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
