# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-22 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0003_auto_20190722_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additonalinfocompany',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='additonalinfoindividual',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='applicantbankdetails',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='asset_details',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='dealersupplier',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='othercredit',
            old_name='is_draft',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='is_draft',
            new_name='is_complete',
        ),
    ]
