# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-23 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0005_applicant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='slug',
        ),
    ]
