# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-24 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0006_remove_applicant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
