# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-24 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0007_applicant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
