# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-24 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0008_applicant_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='User',
            new_name='user_id',
        ),
    ]
