# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-24 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0009_auto_20190724_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantbankdetails',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicantbankdetails',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
